In [3]:
import numpy as np

In [4]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [5]:
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [5]:
big_secret[:,-1].sum()

3154.332495807108

In [8]:
big_secret.shape

(5, 51)

In [12]:
big_secret_5x5 = big_secret[:,:5]

In [16]:
big_secret_5x5.diagonal().sum()

121.37188663699624

In [17]:
big_secret_5x5

array([[14.        , 10.        ,  6.        , 56.        , 40.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [ 0.        ,  1.        ,  4.        ,  9.        , 16.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [14.        , 10.        ,  6.        , 56.        , 40.        ]])

In [77]:
big_secret_5x5_last = big_secret[:,-6::1]

In [79]:
z=1
for i in flip_big_secret.diagonal():
    z=z*i
    print(z)


-1.0
-1.0
1.0
1.0
-1.0


In [ ]:
762595537404.2002

In [78]:
flip_big_secret = np.fliplr(big_secret_5x5_last)

In [56]:
flip_big_secret

array([[ 294.        ,  490.        ,  686.        ,  276.        ,
         460.        ,  644.        ],
       [  33.1662479 ,   33.13608305,   33.10589071,   33.07567082,
          33.04542328,   33.01514804],
       [2500.        , 2401.        , 2304.        , 2209.        ,
        2116.        , 2025.        ],
       [  33.1662479 ,   33.13608305,   33.10589071,   33.07567082,
          33.04542328,   33.01514804],
       [ 294.        ,  490.        ,  686.        ,  276.        ,
         460.        ,  644.        ]])

In [32]:
flip_big_secret[0,-]

644.0

In [54]:
big_secret_5x5_last

array([[ 644.        ,  460.        ,  276.        ,  686.        ,
         490.        ,  294.        ],
       [  33.01514804,   33.04542328,   33.07567082,   33.10589071,
          33.13608305,   33.1662479 ],
       [2025.        , 2116.        , 2209.        , 2304.        ,
        2401.        , 2500.        ],
       [  33.01514804,   33.04542328,   33.07567082,   33.10589071,
          33.13608305,   33.1662479 ],
       [ 644.        ,  460.        ,  276.        ,  686.        ,
         490.        ,  294.        ]])

In [30]:
big_secret_5x5_last[0,-1]

490.0

In [39]:
big_secret[0,-2]

490.0

In [58]:
my_array = np.random.randint(1, 100, (4, 6))

In [64]:
my_array

array([[ 5, 33, 79, 53, 14, 42],
       [19, 73,  0,  0, 92, 73],
       [34, 86,  0,  0, 29, 20],
       [29, 10, 85, 37, 13, 74]])

In [60]:
my_slice = my_array[1:3, 2:4]

In [61]:
my_slice

array([[24,  8],
       [44, 82]])

In [62]:
my_slice[:]=0

In [63]:
my_slice

array([[0, 0],
       [0, 0]])

In [70]:
type(big_secret.shape[0])

int

In [71]:
for i in range(0,big_secret.shape[0]):
    for j in range(0,big_secret.shape[1]):
        if i%2==0 and j%2==0:
            big_secret[i,j]=-1
        elif i%2!=0 and j%2!=0:
            big_secret[i,j]=1
            

In [73]:
big_secret.shape

(5, 51)

In [74]:
big_secret_5x5 = big_secret[:,:5]

In [76]:
big_secret_5x5.diagonal().sum()

-1.0

In [80]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]
