In [1]:
import numpy as np

In [2]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [3]:
great_secret.shape

(100, 3)

In [4]:
great_secret.ndim

2

In [27]:
great_secret

array([[ 0.        ,  4.64158883, 66.66666667],
       [ 1.        ,  4.65700951, 40.        ],
       [ 1.41421356,  4.67232873, 67.33333333],
       [ 1.73205081,  4.68754815, 40.4       ],
       [ 2.        ,  4.70266938, 68.        ],
       [ 2.23606798,  4.71769398, 40.8       ],
       [ 2.44948974,  4.73262349, 68.66666667],
       [ 2.64575131,  4.7474594 , 41.2       ],
       [ 2.82842712,  4.76220316, 69.33333333],
       [ 3.        ,  4.77685618, 41.6       ],
       [ 3.16227766,  4.79141986, 70.        ],
       [ 3.31662479,  4.80589553, 42.        ],
       [ 3.46410162,  4.82028453, 70.66666667],
       [ 3.60555128,  4.83458813, 42.4       ],
       [ 3.74165739,  4.84880759, 71.33333333],
       [ 3.87298335,  4.86294413, 42.8       ],
       [ 4.        ,  4.87699896, 72.        ],
       [ 4.12310563,  4.89097325, 43.2       ],
       [ 4.24264069,  4.90486813, 72.66666667],
       [ 4.35889894,  4.91868473, 43.6       ],
       [ 4.47213595,  4.93242415, 73.333

In [15]:
great_secret[:1,:]

array([[ 0.        ,  4.64158883, 66.66666667]])

In [18]:
np.cos(great_secret[:1,:]).sum()

0.16006721889793019

In [19]:
np.cos(great_secret[:1,:])

array([[ 1.        , -0.07074101, -0.76919177]])

In [20]:
np.sum(great_secret[great_secret>50])

5470.0

In [21]:
great_secret_raw = great_secret.reshape(1,300)

In [22]:
great_secret_raw.shape

(1, 300)

In [29]:
great_secret_raw[0,150]

7.0710678118654755

In [30]:
np.sort(great_secret,axis=0)[-1,:].sum()

115.12148016521353