In [1]:
import numpy as np

In [5]:
students = np.array([[1,135,34,4],
[2,160,43,5],
[3,163,40,4.3],
[4,147,44,5],
[5,138,41,4.7],
[6,149,54,3.9],
[7,136,39,4.2],
[8,154,48,4.9],
[9,137,35,3.7],
[10,165,60,4.6]],dtype=float)

In [6]:
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [9]:
mean = np.mean(students[:,-2])
mean

43.8

In [10]:
median = np.median(students[:,-2])
median

42.0

In [11]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [12]:
corr2 = np.corrcoef(students[:,1], students[:,-1])
corr2

array([[1.        , 0.46293714],
       [0.46293714, 1.        ]])

In [13]:
corr3 = np.corrcoef(students[:,-1], students[:,-2])
corr3

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [14]:
std = np.std(students[:,-1])
std

0.4517742799230607

In [15]:
std_weigth = np.std(students[:,-2])
std_weigth

7.769169839822013

In [16]:
mean_weigth = np.mean(students[:,-2])
mean_weigth

43.8

In [18]:
np.var(students[:,-2])

60.36

In [19]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

In [22]:
new = my_array[1:4,1:4]

In [23]:
new

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [24]:
my_sin = np.sin(my_array)

In [26]:
my_sin.sum()

-0.05812430261413373

In [30]:
my_sin[1:4,1:4] = 1

In [32]:
my_sin.sum()

7.571718421269144